version: '2'
services:
  web:
    build: .
    command: /bin/bash ./start.sh
    ports:
     - "8000:80"
    volumes:
     - .:/usr/share/nginx/html:rw
    depends_on:
     - db
  db:
    image: orchardup/mysql
    ports:
     - "3306:3306"